import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import axios from 'axios'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.tsx'
import AuthGate from './components/Auth/AuthGate'

// Send cookies on every request (needed for the auth session cookie).
axios.defaults.withCredentials = true

// Auto-redirect to login on any 401 from the API (covers session expiry
// mid-session and any unauthenticated request from a child component).
let _redirecting = false
axios.interceptors.response.use(
  (r) => r,
  (err) => {
    if (err?.response?.status === 401 && !err?.config?.url?.includes('/auth/') && !_redirecting) {
      _redirecting = true
      window.location.replace('/app')
    }
    return Promise.reject(err)
  },
)

// Register service worker (generated by vite-plugin-pwa).
// autoUpdate: the SW updates itself in the background without a prompt.
registerSW({ immediate: true })

// Handle navigation messages from the service worker (notification clicks)
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.addEventListener('message', (event: MessageEvent) => {
    if (event.data?.type === 'NAVIGATE_TICKER') {
      const ticker: string = event.data.ticker
      if (ticker) {
        // Dispatch a custom DOM event that App.tsx can listen to
        window.dispatchEvent(new CustomEvent('sw:navigate-ticker', { detail: { ticker } }))
      }
    }
  })
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <AuthGate>
      <App />
    </AuthGate>
  </StrictMode>,
)
